# Generated by Django 5.2.5 on 2026-01-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
