# Generated by Django 5.2.5 on 2026-02-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
    ]
