from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),

    path('admin-dashboard/', views.adminDashboardView, name='adminDashboard'),
    path('admin-panel/providers/', views.adminProvidersView, name='adminProviders'),
    path('admin-panel/providers/<int:providerId>/approve/', views.approveProvider, name='approveProvider'),
    path('admin-panel/providers/<int:providerId>/deactivate/', views.deactivateProvider, name='deactivateProvider'),
    path('admin-panel/categories/', views.adminCategoriesView, name='adminCategories'),
    path('admin-panel/categories/<int:categoryId>/edit/', views.adminCategoryEdit, name='adminCategoryEdit'),
    path('admin-panel/categories/<int:categoryId>/toggle/', views.adminCategoryToggle, name='adminCategoryToggle'),
    path('admin-panel/packages/', views.adminPackagesView, name='adminPackages'),
    path('admin-panel/packages/<int:packageId>/edit/', views.adminPackageEdit, name='adminPackageEdit'),
    path('admin-panel/packages/<int:packageId>/toggle/', views.adminPackageToggle, name='adminPackageToggle'),
    path('admin-panel/venues/', views.adminVenuesView, name='adminVenues'),
    path('admin-panel/venues/<int:venueId>/edit/', views.adminVenueEdit, name='adminVenueEdit'),
    path('admin-panel/venues/<int:venueId>/toggle/', views.adminVenueToggle, name='adminVenueToggle'),
    path('admin-panel/custom-requests/', views.adminCustomRequests, name='adminCustomRequests'),
    path('admin-panel/custom-requests/<int:requestId>/', views.adminCustomRequestDetail, name='adminCustomRequestDetail'),
    path('admin-panel/orders/', views.adminOrdersView, name='adminOrders'),
    path('admin-panel/orders/<int:orderId>/', views.adminOrderDetail, name='adminOrderDetail'),
    path('provider-dashboard/', views.providerDashboardView, name='providerDashboard'),
    path('provider/tasks/', views.providerTasksView, name='providerTasks'),
    path('provider/tasks/<int:taskId>/update/', views.providerTaskUpdate, name='providerTaskUpdate'),
    path('customer-dashboard/', views.customerDashboardView, name='customerDashboard'),
    path('register/customer/', views.customerRegisterView, name='customerRegister'),
    path('register/provider/', views.providerRegisterView, name='providerRegister'),
    path('customer/customPackage/', views.customPacakgeView, name='customPackage'),
    path('customer/customPackagesRequest/',views.myCustomPackages, name='myCustomPackages'),
    path('customer/categories/', views.categoriesListView, name='categoryList'),
    path('cutomer/categories/packages/<int:categoryId>/', views.packageList, name='packageList'),
    path('customer/categories/packages/detail/<int:packageId>/', views.packageDetail, name='packageDetail'),
    path('customer/categories/packages/detail/<int:packageId>/order/', views.createOrder, name='createOrder'),
    path('customer/orders/', views.customerOrder, name='customerOrder'),
    path('customer/orders/<int:orderId>/', views.orderDetail, name='orderDetail'),
    path('customer/orders/<int:orderId>/cancel/', views.cancelOrder, name='cancelOrder'),
]
